### ISSUE TITLE
Segfault - possibly caused by large sample size?

### ISSUE THREAD

**Issue by DarrenObbard** [kousathanas/MultiDFE#1]
Hi Thanasis!

I am getting another segfault. This is on a simulation that has a large number of samples (2592 haplotypes sampled) and my suspicion is that MultiDFE sets a maximum sample or DFE size, and then doesn't check the input. (I note that dfe-alpha also sets an arbitrary compile-time maximum on this, but did screen the input.)

# My first guess is that it is caused by 

Multi_DFE_est_v1.0.c:	int max_sfs_size=2000;

#but then but then worryingly a few lines later

char sfsname[2000]

#looks like it might be assuming the same limit, but not using the max_sfs_size to set it? 

# My other thought is that it might be caused by 

bctmat01.hd:	#define maxn 2000
bctmat01.hd:	#define maxnd 2*maxn

#but then this same global is defined differently here:

Library_DFE_v1.0.h:	#define maxnd 10000

**Comment by kousathanas** [comment]
Hi @DarrenObbard and thank you for reporting this issue.

The limit is indeed 2000 entries for the sfs, but the second variable that you quote (sfsname) is not related to the sfssize. Its a legacy variable for the size of the string of the name for the sfs filename.

I have now updated the code to remove limits on the size of the provided sfs. The appropriate size is read directly from the provided file and memory for it is allocated.

Would be great if you can pull the latest version and re-compile and test with your dataset. As larger sample sizes could take more time to analyse, you could try running with "conpop 1" i.e, constant population to see whether it seems to be working.

Please let me know if you get into further issues and thanks a lot for the feedback!
